// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef main_h
#define main_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
extern Fl_Group *grpInput;
#include <FL/Fl_Input.H>
extern Fl_Input *txtPassword;
extern Fl_Input *txtCalculationsPerSecond;
#include <FL/Fl_Return_Button.H>
extern Fl_Return_Button *btnSubmit;
extern Fl_Group *grpOutput;
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *txtOutput;
#endif
